<a href="https://colab.research.google.com/github/antraraj441/OIBSIP/blob/main/AntraRaj_3_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("messy_customer_data.csv")

df.head()

  Customer_ID    Name   Age  Gender    Join_Date Salary       City  Rating
0        C001   Aarav  22.0    Male   01/15/2025  52000     Jaipur     4.2
1        C002   Priya  29.0  female   15-01-2025  48000      Delhi     4.5
2        C003   Rohan   NaN       M   2025/01/17  55000     Mumbai     4.0
3        C004   Sneha  35.0  Female  18 Jan 2025  60000  Bangalore     NaN
4        C005  Vikram  41.0    male     19-01-25  75000      Delhi     4.7

In [16]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 30
Columns: 8

In [17]:
original_df = df.copy()

Check basic information

In [2]:
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

Shape: (32, 8)

Data Types:
Customer_ID     object
Name            object
Age            float64
Gender          object
Join_Date       object
Salary          object
City            object
Rating         float64
dtype: object

Missing Values:
Customer_ID    0
Name           0
Age            2
Gender         0
Join_Date      0
Salary         1
City           1
Rating         2
dtype: int64

Duplicate Rows: 2

Data Quality Report

In [3]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Null_Count": df.isnull().sum().values,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": df.nunique().values
})

quality_report

        Column  Null_Count Data_Type  Unique_Values
0  Customer_ID           0    object             30
1         Name           0    object             30
2          Age           2   float64             24
3       Gender           0    object              6
4    Join_Date           0    object             30
5       Salary           1    object             26
6         City           1    object              4
7       Rating           2   float64             13

In [4]:
df.describe()

              Age     Rating
count   30.000000  30.000000
mean    33.366667   4.356667
std     18.720233   0.353976
min     -5.000000   3.800000
25%     26.250000   4.100000
50%     30.500000   4.300000
75%     36.750000   4.575000
max    120.000000   5.500000

Check Duplicate Rows

In [5]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 2

In [6]:
df[df.duplicated()]

   Customer_ID   Name   Age  Gender   Join_Date Salary    City  Rating
20        C008  Meera  26.0  female  22/01/2025  53000  Mumbai     4.6
21        C013  Rahul  28.0    Male  27-01-2025  50000   Delhi     4.2

In [7]:
df = df.drop_duplicates()

print("Duplicates after cleaning:", df.duplicated().sum())

Duplicates after cleaning: 0

Missing Data Analysis

In [8]:
missing = df.isnull().sum()

print(missing)

Customer_ID    0
Name           0
Age            2
Gender         0
Join_Date      0
Salary         1
City           1
Rating         2
dtype: int64

In [9]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report

             Missing_Count  Missing_Percentage
Customer_ID              0            0.000000
Name                     0            0.000000
Age                      2            6.666667
Gender                   0            0.000000
Join_Date                0            0.000000
Salary                   1            3.333333
City                     1            3.333333
Rating                   2            6.666667

Handle Missing Values

In [13]:
# Fill missing Age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Salary with median
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

# Fill missing City with mode
df["City"] = df["City"].fillna(df["City"].mode()[0])

# Fill missing Rating with median
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

# Check missing values
print(df.isnull().sum())

Customer_ID    0
Name           0
Age            0
Gender         0
Join_Date      0
Salary         0
City           0
Rating         0
dtype: int64

Standardise Inconsistent Formatting

In [15]:
# Standardise Gender
df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()

df["Gender"] = df["Gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})

print(df["Gender"].value_counts())

Gender
Male      15
Female    15
Name: count, dtype: int64

In [18]:
df["City"] = df["City"].astype(str).str.strip().str.title()

print(df["City"].value_counts())

City
Delhi        9
Jaipur       8
Mumbai       7
Bangalore    6
Name: count, dtype: int64

In [20]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

In [21]:
print(df["Join_Date"].head())

0   2025-01-15
1          NaT
2          NaT
3          NaT
4          NaT
Name: Join_Date, dtype: datetime64[ns]

Data Type Correction

In [22]:
print(df.dtypes)

Customer_ID            object
Name                   object
Age                   float64
Gender                 object
Join_Date      datetime64[ns]
Salary                float64
City                   object
Rating                float64
dtype: object

In [23]:
df["Customer_ID"] = df["Customer_ID"].astype("string")

In [24]:
df["Age"] = df["Age"].astype(float)
df["Salary"] = df["Salary"].astype(float)
df["Rating"] = df["Rating"].astype(float)

In [25]:
df["Gender"] = df["Gender"].astype("category")
df["City"] = df["City"].astype("category")

In [26]:
print(df.dtypes)

Customer_ID    string[python]
Name                   object
Age                   float64
Gender               category
Join_Date      datetime64[ns]
Salary                float64
City                 category
Rating                float64
dtype: object

Detect Invalid Age values

In [27]:
invalid_age = df[(df["Age"] < 0) | (df["Age"] > 100)]

print(invalid_age)

   Customer_ID   Name    Age  Gender  Join_Date   Salary    City  Rating
22        C021   Aman   -5.0    Male        NaT  52000.0   Delhi     4.0
23        C022  Naina  120.0  Female 2025-05-02  54000.0  Jaipur     4.3

In [28]:
df.loc[(df["Age"] < 0) | (df["Age"] > 100), "Age"] = np.nan

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [30]:
print(df["Age"].describe())

count    30.000000
mean     31.866667
std       6.038573
min      22.000000
25%      27.250000
50%      31.000000
75%      35.750000
max      45.000000
Name: Age, dtype: float64

Outlier Detection Using IQR

In [31]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 52000.0
Q3: 62750.0
IQR: 10750.0

In [32]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Lower Limit: 35875.0
Upper Limit: 78875.0

In [33]:
salary_outliers = df[
    (df["Salary"] < lower_limit) |
    (df["Salary"] > upper_limit)
]

print("Number of Salary Outliers:", len(salary_outliers))

salary_outliers

Number of Salary Outliers: 2

   Customer_ID    Name   Age Gender Join_Date    Salary   City  Rating
8         C009   Arjun  45.0   Male       NaT   82000.0  Delhi     4.8
16        C017  Aditya  44.0   Male       NaT  150000.0  Delhi     4.9

Detect Rating Anomaly

In [35]:
invalid_rating = df[
    (df["Rating"] < 1) |
    (df["Rating"] > 5)
]

print(invalid_rating)

   Customer_ID   Name   Age Gender  Join_Date   Salary   City  Rating
26        C025  Mohit  40.0   Male 2025-08-02  61000.0  Delhi     5.5

In [36]:
df.loc[
    (df["Rating"] < 1) | (df["Rating"] > 5),
    "Rating"
] = np.nan

In [37]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

In [38]:
print(df["Rating"].describe())

count    30.000000
mean      4.310000
std       0.274616
min       3.800000
25%       4.100000
50%       4.300000
75%       4.500000
max       4.900000
Name: Rating, dtype: float64

Final Missing Value Check

In [39]:
print("Missing values after cleaning:")

print(df.isnull().sum())

Missing values after cleaning:
Customer_ID     0
Name            0
Age             0
Gender          0
Join_Date      25
Salary          0
City            0
Rating          0
dtype: int64

Final Duplicate Check

In [40]:
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

Final Data Types

In [41]:
print(df.dtypes)

Customer_ID    string[python]
Name                   object
Age                   float64
Gender               category
Join_Date      datetime64[ns]
Salary                float64
City                 category
Rating                float64
dtype: object

Before vs After Summary

In [42]:
before_summary = {
    "Row Count": len(original_df),
    "Column Count": len(original_df.columns),
    "Null Count": original_df.isnull().sum().sum(),
    "Duplicate Count": original_df.duplicated().sum()
}

after_summary = {
    "Row Count": len(df),
    "Column Count": len(df.columns),
    "Null Count": df.isnull().sum().sum(),
    "Duplicate Count": df.duplicated().sum()
}

In [43]:
comparison = pd.DataFrame({
    "Before Cleaning": before_summary,
    "After Cleaning": after_summary
})

comparison

                 Before Cleaning  After Cleaning
Row Count                     30              30
Column Count                   8               8
Null Count                     0              25
Duplicate Count                0               0

Compare Data Types

In [44]:
dtype_comparison = pd.DataFrame({
    "Before": original_df.dtypes.astype(str),
    "After": df.dtypes.astype(str)
})

dtype_comparison

              Before           After
Customer_ID   object          string
Name          object          object
Age          float64         float64
Gender        object        category
Join_Date     object  datetime64[ns]
Salary       float64         float64
City          object        category
Rating       float64         float64

Final Dataset Inspection

In [45]:
print("Final Dataset Shape:", df.shape)

print("\nFirst 5 rows:")
display(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final Dataset Shape: (30, 8)

First 5 rows:

  Customer_ID    Name   Age  Gender  Join_Date   Salary       City  Rating
0        C001   Aarav  22.0    Male 2025-01-15  52000.0     Jaipur     4.2
1        C002   Priya  29.0  Female        NaT  48000.0      Delhi     4.5
2        C003   Rohan  31.0    Male        NaT  55000.0     Mumbai     4.0
3        C004   Sneha  35.0  Female        NaT  60000.0  Bangalore     4.3
4        C005  Vikram  41.0    Male        NaT  75000.0      Delhi     4.7

Missing Values:
Customer_ID     0
Name            0
Age             0
Gender          0
Join_Date      25
Salary          0
City            0
Rating          0
dtype: int64

Duplicate Rows:
0

Data Types:
Customer_ID    string[python]
Name                   object
Age                   float64
Gender               category
Join_Date      datetime64[ns]
Salary                float64
City                 category
Rating                float64
dtype: object

Save Clean Dataset

In [46]:
df.to_csv("cleaned_customer_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

Verify Saved Dataset

In [47]:
cleaned_df = pd.read_csv("cleaned_customer_data.csv")

print(cleaned_df.head())
print("\nShape:", cleaned_df.shape)

  Customer_ID    Name   Age  Gender   Join_Date   Salary       City  Rating
0        C001   Aarav  22.0    Male  2025-01-15  52000.0     Jaipur     4.2
1        C002   Priya  29.0  Female         NaN  48000.0      Delhi     4.5
2        C003   Rohan  31.0    Male         NaN  55000.0     Mumbai     4.0
3        C004   Sneha  35.0  Female         NaN  60000.0  Bangalore     4.3
4        C005  Vikram  41.0    Male         NaN  75000.0      Delhi     4.7

Shape: (30, 8)